name: SpeRulesPlugin
version: ${project.version}
main: me.kokored.speserver.sperulesplugin.SpeRulesPlugin
api-version: 1.15
authors: [ Koko_red7214 ]
description: 無語伺服器-條約及規則插件

commands:

  srp:
    description: Plugin main command

  rules:
    aliases: [ rule ]
    description: Open play rules gui

  chatrules:
    aliases: [ chatrule ]
    description: Open chat rules gui
