SQL:
  #MySQL, MariaDB
  Type: 'MySQL'
  host: 'localhost'
  port: 3306
  database: ''
  username: 'minecraft'
  password: 'minecraft'

Discord:
  token: 'BOT TOKEN HERE'
  channel:
    ChatChannel: '000000000000000000'

Setting:
  mcleaks:
    kick: true
