SQL:
  #MySQL, MariaDB
  Type: 'MySQL'
  host: 'localhost'
  port: 3306
  database: ''
  username: 'minecraft'
  password: 'minecraft'

#啓用或關閉某些功能
Features:
  #死亡扣除經驗或金錢
  DeathExp: true
  #自定附魔
  enchantments:
    #快速拾取
    Telepathy: true
  #自定物品
  items:
    QuickPickupInstrument: true