name: SpeManagerPlugin
version: ${project.version}
main: me.kokored.speserver.spemanagerplugin.bukkit.SpeManagerPlugin
api-version: 1.15
authors: [ Koko_red7214 ]
description: 無語伺服器-管理系統
softdepend:
  - Vault

commands:

  switch:
    permission: speserver.managerplugin.command.switch

permissions:

  speserver.managerplugin.command.switch:
    default: true
